version: '2'
volumes:
    resin-data:
services:
  brickdaemon:
    build: ./brickdaemon
    privileged: true
    network_mode: host
  tf-mqtt-bindings:
    build: ./tf-mqtt-bindings
    privileged: true
    network_mode: host
    depends_on:
      - brickdaemon
