version: '2'
volumes:
    resin-data:
services:
  brickdaemon:
    build: ./brickdaemon
    privileged: true
    network_mode: host
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
      - "/dev/spidev0.1:/dev/spidev0.1"
  knxbridge:
    build: ./knxbridge
    privileged: true
    network_mode: host
