FROM balenalib/%%BALENA_MACHINE_NAME%%:latest

# Defines our working directory in container
WORKDIR /usr/src/app

# Copy over the files created in the previous step, including lib/, bin/
RUN apt-get update
RUN apt install -y mosquitto mosquitto-clients

# This will copy all files in our root to the working  directory in the container
COPY . ./

# server.js will run when container starts up on the device
CMD ["bash", "src/start.sh"]
